Декоративные элементы главной страницы
htmlacademy-adaptive/1333157-sedona-22 pull request #11
Opened 2021-04-26 14:02 UTC by EzhovaT

---
:mortar_board: [Декоративные элементы главной страницы](https://up.htmlacademy.ru/adaptive/22/user/1333157/tasks/13)

:boom: https://htmlacademy-adaptive.github.io/1333157-sedona-22/11/

2021-04-27 18:57 UTC, undgrnd requested changes

2021-04-27 18:57 UTC, undgrnd commented on source/index.html
> +      style="display: none;"
О, а это красная карточка)

2021-04-27 18:57 UTC, undgrnd commented on source/index.html
> +                  <picture>
Нужен класс. Всегда нужны классы всему и везде, даже если не будем их стилизовать, потому что во-первых классы они не только про CSS, а еще и про HTML и во-вторых так код HTML становится понятнее, исходный код разметки становится более читабельный — сразу понятно что за элемент по БЭМ и какому блоку он принадлежит

2021-04-27 18:57 UTC, undgrnd commented on source/js/main.js
> +nav.classList.remove("main-nav_no-js");
А вот эта штука разве не при инициализации документа должна происходить?

2021-04-27 18:57 UTC, undgrnd commented on source/sass/blocks/footer-social.scss
> +  position: relative;
А почему relative а не absolute?

2021-04-27 18:57 UTC, undgrnd commented on source/sass/blocks/main-nav.scss
> +.main-nav_closed .nav-list__item {
По БЭМ нельзя чтобы стили одного блока влияли на другой блок

2021-04-27 18:57 UTC, undgrnd commented on source/sass/blocks/main-nav.scss
> +.main-nav_closed .main-nav__toggle {
Что-то тут неладно. Зачем определять тоже самое но и еще дополнительно под модификатором?

2021-04-28 11:14 UTC, EzhovaT commented on source/index.html
> +      style="display: none;"
Исправила

2021-04-28 11:16 UTC, EzhovaT commented on source/index.html
> +                  <picture>
Добавила классы

2021-04-28 11:16 UTC, EzhovaT commented on source/sass/blocks/footer-social.scss
> +  position: relative;
Исправила

2021-04-28 11:17 UTC, EzhovaT commented on source/sass/blocks/main-nav.scss
> +.main-nav_closed .nav-list__item {
Переделала

2021-04-28 11:17 UTC, EzhovaT commented on source/sass/blocks/main-nav.scss
> +.main-nav_closed .main-nav__toggle {
Исправила

2021-05-02 15:07 UTC, mikhin requested changes

2021-05-02 15:07 UTC, mikhin commented on source/index.html
> +          <nav class="main-nav menu-nojs closed-menu">
`closed-menu`, кажется, это должен быть БЭМ-модификатор

2021-05-02 15:07 UTC, mikhin commented on source/index.html
> +              <li class="nav-list__item menu-nojs__item closed-menu__item">
Некруто, что на одном HTML-узле висит аж три элемента от разных БЭМ-блоков: код получился максимально хрупкий; в чем независимость каждого из блоков — непонятно; как эти блоки использовать по отдельности — непонятно;

Го все упростим до одного БЭМ-блока?)

2021-05-02 15:07 UTC, mikhin commented on source/index.html
> +            <button class="main-nav__toggle menu-nojs__btn closed-menu__btn" type="button">
Здесь тоже самое что и выше — сложно и непонятно

2021-05-02 15:07 UTC, mikhin commented on source/sass/blocks/page-sprite.scss
> +.page-sprite {
Что это за блок?)

2021-05-02 16:53 UTC, EzhovaT commented on source/index.html
> +          <nav class="main-nav menu-nojs closed-menu">
Исправила

2021-05-02 16:54 UTC, EzhovaT commented on source/index.html
> +              <li class="nav-list__item menu-nojs__item closed-menu__item">
Исправила

2021-05-02 16:54 UTC, EzhovaT commented on source/index.html
> +            <button class="main-nav__toggle menu-nojs__btn closed-menu__btn" type="button">
Исправила

2021-05-02 16:54 UTC, EzhovaT commented on source/sass/blocks/page-sprite.scss
> +.page-sprite {
Изменить имя класса?

2021-05-02 17:05 UTC, mikhin commented on source/sass/blocks/page.scss
> +.page-sprite {
@EzhovaT  для каждого БЭМ-блока должен быть свой отдельный файл

2021-05-02 17:11 UTC, mikhin approved these changes

2021-05-02 17:11 UTC, merged