Разметка страницы index.html
htmlacademy-adaptive/1333157-sedona-22 pull request #2
Opened 2021-03-26 12:06 UTC by EzhovaT

2021-03-27 15:29 UTC, mikhin requested changes

2021-03-27 15:29 UTC, mikhin commented on source/img/logotype-mobile.svg
> +<svg width="102" height="84" viewBox="0 0 102 84" fill="none" xmlns="http://www.w3.org/2000/svg">
А нам вроде картинки в этом задании не нужно было подготавливать?)

2021-03-27 15:29 UTC, mikhin commented on source/index.html
> +          <ul class="main-nav__list site-list">
site-list не оч понятное имя класса. Читается как "список сайтов")

2021-03-27 15:29 UTC, mikhin commented on source/index.html
> +              <a class="site-list__link"> Главная </a>
Пробелы вокруг текста не нужны)

2021-03-27 15:29 UTC, mikhin commented on source/index.html
> +              <a class="site-list__link"> Главная </a>
Тут надо предусмотреть момент, что пункт меню может быть не ссылкой, т.к. если он активный, т.е. мы находимся на данной странице, он не должен быть ссылкой)

2021-03-27 15:29 UTC, mikhin commented on source/index.html
> +            <li class="site-list__item site-list__item_rigth">
опечатка, right

2021-03-27 15:29 UTC, mikhin commented on source/index.html
> +            <li class="site-list__item site-list__item_rigth">
уже заранее как будто мы чутка готовимся костылить этот чертов логотип, который разрывает нам меню =)

давай пока уберем этот модификатор? сейчас он плох во-первых тем, что он именован исходя из визуального смысла, а не функционального смысла. А во-вторых он вот прям костыльно смотрится) когда будем стилизовать меню и логотип, подумаем как сделать элегантно)

2021-03-27 15:29 UTC, mikhin commented on source/index.html
> +                class="site-list__link site-list__link_uppercase"
Пока непонятно, что такое "site-list__link_uppercase" и почему он единожды используется. Давай уберем пока?)

2021-03-27 15:29 UTC, mikhin commented on source/index.html
> +                HTML academy
Academy с большой буквы)

2021-03-27 15:29 UTC, mikhin commented on source/index.html
> +          <img src="/img/logotype-mobile.svg" alt="City of Sedona" />
Alt давай по русски напишем?)

2021-03-27 15:29 UTC, mikhin commented on source/index.html
> +            src="/img/text-index.svg.svg"
В имени файла опечатка в дублировании расширения файла

2021-03-27 15:29 UTC, mikhin commented on source/index.html
> +            alt="Добро пожаловать в Седону"
alt сейчас бесполезный) он не говорит о том, что изображено на картинке)

2021-03-27 15:29 UTC, mikhin commented on source/index.html
> +        <div class="main-images">
звучит как "главные картинки", что не совсем корректно) можно подумать в сторону "promo-banner" или что-то такое)

2021-03-27 15:29 UTC, mikhin commented on source/index.html
> +        <section class="intro">
Однословные имена классов — почти всегда неполезно, т.к. ничего не говорит о том, что это за элемент. Вот мы открываем список БЭМ-блоков, видим `intro`, и не понимаем что это компонент в интерфейсе? Для чего он нужен и как используется? Непонятно, потому что не хватает термина из нашей с тобой профессиональной области — разработка интерфейсов. Если в именованиях использовать термины из разработки интерфейсов + термины из бизнес-области проекта, то почти всегда именования будут понятны сразу после прочтения, без необходимости глубже погружаться в код)

Вот тут еще глянуть можно — https://github.com/yoksel/common-words

2021-03-27 15:29 UTC, mikhin commented on source/index.html
> +            Седона — небольшой городок в Аризоне, зфслуживающий большего!
опечатка, заслуживающий

2021-03-27 15:29 UTC, mikhin commented on source/index.html
> +          <p class="intro__subtitle">
Класс указан subtitle, а по семантике это параграф — противоречие)

2021-03-27 15:29 UTC, mikhin commented on source/index.html
> +            Рассмотрим 5 причин, по которым Седона круче, чем гранд каньон!
Гранд-Каньон

2021-03-27 15:29 UTC, mikhin commented on source/index.html
> +        <section class="advantages advantages-list">
Пока непонятно зачем на одной ноде висят два БЭМ-блока)

2021-03-27 15:29 UTC, mikhin commented on source/index.html
> +          <div class="advantages__item">
Если item у нас тут, то давай по семантике и сделаем список?)

2021-03-27 15:29 UTC, mikhin commented on source/index.html
> +            <div class="advantages-text advantages-text_light">
Непонятно что такое `advantages-text`. Вообще слово `text` в именовании почти всегда бесполезно использовать, т.к. ничего понятного это слово не приносит) У нас тут все текст — и код, и разметка, и HTML и семантика — это все текст)

2021-03-27 15:29 UTC, mikhin commented on source/index.html
> +            <div class="advantages-image advantages-image_right">
Пока не оч понятно имеет ли смысл картинку и текст выше выносить в отдельные БЭМ-блоки. Если считаешь, что смысл есть — тогда не нужно завязывать их использование на блок `advantages` исходя из именования, т.к. БЭМ-блок — это абсолютно-независимый блок и должен хотеть быть таким. А тут они как будто знают где и как они будут использоваться)

2021-03-27 15:29 UTC, mikhin commented on source/index.html
> +                class="advantages-image__foto"
__photo

2021-03-27 15:29 UTC, mikhin commented on source/index.html
> +              <h3 class="advantages__title card__title">Жилье</h3>
Вот тут сейчас получилось оч-оч хрупко, т.к. одна нода зависит от двух БЭМ-элементов, т.е. они срощены костьми друг с другом, а должны быть возможны использоваться и по отдельности.

2021-03-27 15:29 UTC, mikhin commented on source/index.html
> +            Найти гостинницу
гостиницу

2021-03-27 15:29 UTC, mikhin commented on source/index.html
> +            предложения гостиниц в седоне
Седоне

2021-03-27 15:29 UTC, mikhin commented on source/index.html
> +        <a class="footer-haschtag" href="#">#Visitsedona</a>
hashtag

2021-03-27 15:29 UTC, mikhin commented on source/index.html
> +          <ul class="social__list">
Не хватает родительского БЭМ-блока

2021-03-27 15:52 UTC, EzhovaT commented on source/index.html
> +              <a class="site-list__link"> Главная </a>
не понимаю как это сделать. Если мы находимся на главной, то <a> будет <p>?

2021-03-27 15:53 UTC, EzhovaT commented on source/index.html
> +              <a class="site-list__link"> Главная </a>
то ссылка будет параграфом?

2021-03-27 15:57 UTC, EzhovaT commented on source/index.html
> +            alt="Добро пожаловать в Седону"
т.е его совсем убрать, или описать по другому?

2021-03-27 16:26 UTC, EzhovaT commented on source/index.html
> +            Рассмотрим 5 причин, по которым Седона круче, чем гранд каньон!
В этом месте в макете написано без дефиса, стоит исправить?

2021-03-27 16:42 UTC, EzhovaT commented on source/index.html
> +          <ul class="main-nav__list site-list">
исправила

2021-03-27 16:43 UTC, EzhovaT commented on source/index.html
> +            <li class="site-list__item site-list__item_rigth">
исправила

2021-03-27 16:44 UTC, EzhovaT commented on source/index.html
> +          <img src="/img/logotype-mobile.svg" alt="City of Sedona" />
исправила

2021-03-27 16:44 UTC, EzhovaT commented on source/index.html
> +            src="/img/text-index.svg.svg"
исправила

2021-03-27 16:45 UTC, EzhovaT commented on source/index.html
> +        <div class="main-images">
исправила

2021-03-27 16:45 UTC, EzhovaT commented on source/index.html
> +            Седона — небольшой городок в Аризоне, зфслуживающий большего!
исправила

2021-03-27 16:48 UTC, EzhovaT commented on source/index.html
> +          <p class="intro__subtitle">
исправила

2021-03-27 16:48 UTC, EzhovaT commented on source/index.html
> +        <section class="advantages advantages-list">
исправила

2021-03-27 16:49 UTC, EzhovaT commented on source/index.html
> +          <div class="advantages__item">
переделала

2021-03-27 16:50 UTC, EzhovaT commented on source/index.html
> +            <div class="advantages-text advantages-text_light">
можно заменить на text-box?

2021-03-27 16:54 UTC, EzhovaT commented on source/index.html
> +            <div class="advantages-image advantages-image_right">
скорее всего картинку можно оставить и без блока. исправила

2021-03-27 16:54 UTC, EzhovaT commented on source/index.html
> +                class="advantages-image__foto"
Исправила

2021-03-27 17:01 UTC, EzhovaT commented on source/index.html
> +              <h3 class="advantages__title card__title">Жилье</h3>
Оставила один класс

2021-03-27 17:03 UTC, EzhovaT commented on source/index.html
> +            Рассмотрим 5 причин, по которым Седона круче, чем гранд каньон!
И в строке 132 такая же ситуация

2021-03-27 17:03 UTC, EzhovaT commented on source/index.html
> +            Найти гостинницу
Исправила

2021-03-27 17:03 UTC, EzhovaT commented on source/index.html
> +            предложения гостиниц в седоне
Исправила

2021-03-27 17:04 UTC, EzhovaT commented on source/index.html
> +        <a class="footer-haschtag" href="#">#Visitsedona</a>
исправила

2021-03-27 17:09 UTC, EzhovaT commented on source/index.html
> +          <ul class="social__list">
исправила

2021-03-27 17:12 UTC, EzhovaT commented on source/img/logotype-mobile.svg
> +<svg width="102" height="84" viewBox="0 0 102 84" fill="none" xmlns="http://www.w3.org/2000/svg">
В задании написано "Необходимые изображения можно экспортировать из Figma." Я подумала что имеется ввиду вставить в верстку

2021-03-27 17:13 UTC, EzhovaT commented on source/index.html
> +              <a class="site-list__link"> Главная </a>
исправила

2021-03-28 15:59 UTC, mikhin commented on source/img/logotype-mobile.svg
> +<svg width="102" height="84" viewBox="0 0 102 84" fill="none" xmlns="http://www.w3.org/2000/svg">
Окей)

2021-03-28 15:59 UTC, mikhin commented on source/img/text-index.svg.svg
> +<svg width="282" height="214" viewBox="0 0 282 214" fill="none" xmlns="http://www.w3.org/2000/svg">
@EzhovaT ,  в имени файла опечатка)

2021-03-28 16:00 UTC, mikhin commented on source/index.html
> +            alt="Добро пожаловать в Седону"
Описать по другому)

2021-03-28 16:00 UTC, mikhin commented on source/index.html
> +          <ul class="social__list">
Однословное имя класса — не очень)

2021-03-28 16:01 UTC, mikhin commented on source/index.html
> +              <a class="site-list__link"> Главная </a>
Нет, элемент будет span например, т.к. и ссылка и span — оба строчные элементы, их достаточно легко заменить в разметке друг другом, чтобы верстка не сломалась)

2021-03-28 16:03 UTC, mikhin commented on source/index.html
> +            Рассмотрим 5 причин, по которым Седона круче, чем гранд каньон!
Лучше написать по правилам русского языка, да)

2021-03-28 16:04 UTC, mikhin commented on source/index.html
> +          <ul class="advantages-list">
Опечатка по БЭМ? Или отдельный БЭМ блок? Если да, то зачем?)

2021-03-28 16:04 UTC, mikhin commented on source/index.html
> +              <div class="advantages-text-box advantages-text-box_light">
Непонятно зачем нужен отдельный БЭМ-блок, если у него внутри нет своих элементов)

2021-03-28 16:05 UTC, mikhin commented on source/index.html
> +                <h3 class="advantages__title card__title">Красивая дорога</h3>
Тут остался баг, когда на одной ноде висят два БЭМ-элемента)

2021-03-28 16:05 UTC, mikhin commented on source/index.html
> +                <p class="advantages__description card__description">
Тут остался баг, когда на одной ноде висят два БЭМ-элемента)

2021-03-28 16:06 UTC, mikhin commented on source/index.html
> +            <div class="advantages-text advantages-text_light">
Не, слово `text` не говорит тут ни о чем) Что за "текстовая область"? Тут же все у нас сплошь одни текстовые области)

2021-03-28 16:06 UTC, merged

2021-03-28 16:28 UTC, EzhovaT commented on source/img/text-index.svg.svg
> +<svg width="282" height="214" viewBox="0 0 282 214" fill="none" xmlns="http://www.w3.org/2000/svg">
исправила

2021-03-28 16:29 UTC, EzhovaT commented on source/index.html
> +          <ul class="social__list">
изменила везде на footer-social

2021-03-28 16:29 UTC, EzhovaT commented on source/index.html
> +              <a class="site-list__link"> Главная </a>
исправила

2021-03-28 17:59 UTC, EzhovaT commented on source/index.html
> +            <div class="advantages-text advantages-text_light">
а info-box? )

2021-03-28 18:02 UTC, EzhovaT commented on source/index.html
> +          <ul class="advantages-list">
исправила

2021-03-28 18:03 UTC, EzhovaT commented on source/index.html
> +              <div class="advantages-text-box advantages-text-box_light">
исправила

2021-03-28 18:04 UTC, EzhovaT commented on source/index.html
> +                <h3 class="advantages__title card__title">Красивая дорога</h3>
Исправила

2021-03-28 18:07 UTC, EzhovaT commented on source/index.html
> +            alt="Добро пожаловать в Седону"
Исправила

2021-03-28 18:07 UTC, EzhovaT commented on source/index.html
> +        <section class="intro">
исправила

2021-03-28 18:08 UTC, EzhovaT commented on source/index.html
> +            Рассмотрим 5 причин, по которым Седона круче, чем гранд каньон!
Исправила