Module3 task1
htmlacademy-adaptive/1333157-sedona-22 pull request #5
Opened 2021-04-02 05:26 UTC by EzhovaT

2021-04-02 08:01 UTC, mikhin commented
@EzhovaT , сейчас есть ошибки в консоли
![Uploading Screenshot 2021-04-02 at 11.01.34.png…]()

2021-04-02 08:03 UTC, mikhin commented
Давай ссылку в логотипе сделаем блочной?)
<img width="246" alt="Screenshot 2021-04-02 at 11 02 58" src="https://user-images.githubusercontent.com/38258318/113395767-094e2280-93a3-11eb-8477-9f357dfb0fd9.png">

2021-04-02 08:13 UTC, mikhin commented
Давай поправим, чтобы отступ не залезал за пределы родителя?)
<img width="1270" alt="Screenshot 2021-04-02 at 11 12 11" src="https://user-images.githubusercontent.com/38258318/113396577-65657680-93a4-11eb-8e15-d186b04e9c1c.png">

2021-04-02 08:13 UTC, mikhin commented
<img width="942" alt="Screenshot 2021-04-02 at 11 13 29" src="https://user-images.githubusercontent.com/38258318/113396625-79a97380-93a4-11eb-93a3-4281ced374cb.png">

Давай поправим чтобы отступы не заезжали на нижний элемент?)

2021-04-02 08:14 UTC, mikhin requested changes

2021-04-02 08:14 UTC, mikhin commented on source/sass/global/fonts.scss
> +  font-family: "PT Sans Narrow", "Tahoma", sans-serif;
При определении @font-face, в свойстве font-family указывается только имя шрифта, как оно будет использоваться в стилях

https://developer.mozilla.org/ru/docs/Web/CSS/@font-face

2021-04-02 08:14 UTC, mikhin commented on source/index.html
>          <div class="main-slogan">
Не похоже по макету, кстати, что main-slogan это часть шапки

2021-04-02 08:14 UTC, mikhin commented on source/sass/blocks/main-advantages.scss
> +  padding-bottom: 35px;
По коду непонятно почему тут только нижний паддинг, а верхний на родителе
<img width="534" alt="Screenshot 2021-04-02 at 11 05 22" src="https://user-images.githubusercontent.com/38258318/113395964-60ec8e00-93a3-11eb-8f9e-1cf3b840faf9.png">

2021-04-02 08:14 UTC, mikhin commented on source/index.html
> +              <div class="main-advantages__wrapper">
Давай эту карточку вынесем из main-advantages и сделаем отдельным БЭМ-блоком? Иначе `main-advantages` получается уж слишком жадный и сложный

2021-04-02 08:14 UTC, mikhin commented on source/index.html
>                  <p class="main-advantages__title">Настоящий городок</p>
Давай сделаем по семантике заголовок?)

2021-04-02 08:14 UTC, mikhin commented on source/index.html
> +              class="main-advantages__info-box main-advantages__info-box_light"
Вроде бы пока модификатор и не нужен, т.к. по другому элемент пока не используется)

2021-04-02 08:14 UTC, mikhin commented on source/index.html
> +            >
Давай добавим текстовые описания в ссылки? Чтобы они стали более доступными)

2021-04-03 04:34 UTC, EzhovaT commented on package-lock.json
> +  "name": "sedona-22",
не могу ответить) может после выбора препроцессора

2021-04-03 04:38 UTC, EzhovaT commented on source/index.html
> -    <div class="page-wrapper">
я подумала о том, что нужно каждой секции давать обертку для отступов. а этим page-wrapper отступы сделать не получается. Или им нужно фиксировать ширину всего контента страницы? сделать его как контейнером для страницы?

2021-04-03 05:11 UTC, EzhovaT commented on source/sass/blocks/footer-hashtag.scss
> +  color: rgb(0, 0, 0);
Сделала

2021-04-03 05:22 UTC, EzhovaT commented on source/sass/blocks/advantages-card.scss
> +.advantages-card_gray {
Исправила

2021-04-03 05:40 UTC, EzhovaT commented on source/sass/blocks/advantages-card.scss
> +    width: 39px;
Исправила

2021-04-03 05:55 UTC, EzhovaT commented on source/sass/blocks/main-advantages.scss
> +.main-advantages__item_gray {
Исправила

2021-04-03 06:05 UTC, EzhovaT commented on source/sass/blocks/main-slogan.scss
> +  padding-top: 90px;
Исправила

2021-04-03 06:09 UTC, EzhovaT commented on source/sass/global/fonts.scss
> +  font-family: "PT Sans Narrow", "Tahoma", sans-serif;
Исправила

2021-04-03 06:15 UTC, EzhovaT commented on source/index.html
>          <div class="main-slogan">
ну да, скорее всего так. Исправила

2021-04-03 06:24 UTC, EzhovaT commented on source/sass/blocks/main-advantages.scss
> +  padding-bottom: 35px;
Исправила

2021-04-03 06:26 UTC, EzhovaT commented on source/index.html
>                  <p class="main-advantages__title">Настоящий городок</p>
Исправила

2021-04-03 06:27 UTC, EzhovaT commented on source/index.html
> +              class="main-advantages__info-box main-advantages__info-box_light"
Исправила

2021-04-03 06:36 UTC, EzhovaT commented on source/index.html
> +            >
текстовое описание в атрибуте title, правильно?

2021-04-03 06:47 UTC, EzhovaT commented on source/sass/blocks/advantages-card.scss
> +  margin-bottom: 29px;
Можно каждой карточке с иконкой (advantages-card advantages-card_house), сделать свой wrapper?

2021-04-03 06:47 UTC, EzhovaT commented on source/sass/blocks/main-advantages.scss
> +.main-advantages__list {
Вроде исправила)

2021-04-03 06:49 UTC, EzhovaT commented on source/sass/blocks/main-slogan.scss
> +  height: 100vh;
Исправила

2021-04-03 13:53 UTC, EzhovaT commented on source/index.html
> +              <div class="main-advantages__wrapper">
Сделала

2021-04-03 13:55 UTC, EzhovaT commented on source/sass/blocks/advantages-card.scss
> +.advantages-card_gray {
Сделала все виды карточек отдельными блоками

2021-04-03 15:21 UTC, EzhovaT commented on source/sass/blocks/advantages-card.scss
> +.advantages-card_house {
Исправила

2021-04-03 19:22 UTC, mikhin commented on source/index.html
> +            >
не, насколько я понимаю, описание в атрибуте title не делает ссылку максимально доступной. Можно использовать aria-атрибуты, а можно прям бахнуть текст в ссылку и скрыть потом его через font-size: 0 в CSS)

2021-04-03 19:23 UTC, mikhin commented on source/sass/blocks/advantages-card.scss
> +  margin-bottom: 29px;
@EzhovaT отдельный БЭМ-блок? Если это имеешь ввиду, то нет) Нужно примиксовать элемент от другого БЭМ-блока)

2021-04-03 19:23 UTC, mikhin commented on source/index.html
> -    <div class="page-wrapper">
нууу, например да)

2021-04-03 19:28 UTC, mikhin approved these changes

2021-04-03 19:28 UTC, mikhin commented on source/index.html
> +          <div class="main-tagline__inner-wrapper">
Что-то много врапперов получилось) может одним общим сможем обойтись?)

2021-04-03 19:28 UTC, mikhin commented on source/index.html
> +            <li class="main-advantages__item main-advantages__item_special">
`special` чисто по коду непонятно что означает)

2021-04-03 19:28 UTC, mikhin commented on source/index.html
> +              <div class="special-card">
special чисто по коду непонятно что означает)

2021-04-03 19:28 UTC, mikhin commented on source/sass/blocks/footer-social.scss
> +.footer-social__link_twitter,
А тут можно ведь просто написать?

```
.footer-social__link {
  &::before {
  }
}
```

2021-04-03 19:28 UTC, mikhin commented on source/sass/blocks/special-card.scss
> +  margin: 0 auto;
выравнивание БЭМ-блока не должно быть на самом блоке, а должно быть на миксе-элемент от его родителя)

2021-04-03 19:29 UTC, merged

2021-04-04 07:34 UTC, EzhovaT commented on source/sass/blocks/special-card.scss
> +  margin: 0 auto;
исправила

2021-04-04 07:34 UTC, EzhovaT commented on source/sass/blocks/footer-social.scss
> +.footer-social__link_twitter,
исправила

2021-04-04 07:35 UTC, EzhovaT commented on source/index.html
> +            >
Сделала

2021-04-04 08:11 UTC, EzhovaT commented on source/index.html
> +          <div class="main-tagline__inner-wrapper">
Сделала отдельный класс inner-wrapper и буду добавлять его где нужны эти свойства, а div.main-tagline__inner-wrapper убрала.  так можно делать?