Стилизация страницы формы
htmlacademy-adaptive/1333157-sedona-22 pull request #6
Opened 2021-04-04 15:40 UTC by EzhovaT

2021-04-05 07:58 UTC, mikhin requested changes

2021-04-05 07:58 UTC, mikhin commented on source/catalog.html
> +    <link rel="stylesheet" href="css/style.css" />
Это вроде необязательно?

2021-04-05 07:58 UTC, mikhin commented on source/form.html
> +          <hr class="page-form__line" />
Чисто по коду непонятно что за элемент "линия"

2021-04-05 07:58 UTC, mikhin commented on source/form.html
> +                  class="form-group__input user-form__input"
Давай все виды инпутов сделаем отдельными БЭМ-блоками?

2021-04-05 07:58 UTC, mikhin commented on source/form.html
> +                <label
Давай поле формы сделаем отдельным БЭМ-блоком? При этом, чтобы в него можно было вложить любой инпут)

2021-04-05 07:58 UTC, mikhin commented on source/form.html
> +            <ul class="form-group__list contact-form">
По идее это не отдельные формы, а одна большая, поэтому отдельные БЭМ-блоки вызывают сомнение)

2021-04-05 07:58 UTC, mikhin commented on source/form.html
> +          <hr class="page-form__line" />
По идее не должны хотеть вот так декорировать страницу через HTML) лучше это сделать через CSS)

2021-04-05 07:58 UTC, mikhin commented on source/form.html
> +                  <span class="impression-form__input-decor"></span>
По идее не должны хотеть вот так декорировать страницу через HTML) лучше это сделать через CSS)

2021-04-05 07:58 UTC, mikhin commented on source/form.html
> +                  <p class="impression-form__label-desc">
А внутри строчного label разве может быть блочный абзац? Проверишь валидацию?

2021-04-05 07:58 UTC, mikhin commented on source/form.html
> +                >Ссыкла на социальную сеть twitter
Опечатка

2021-04-05 07:58 UTC, mikhin commented on source/sass/blocks/contact-form.scss
> +  background-image: url("../img/phone.svg");
Еще удобно svg сразу инлайнить, чтобы не хранить в файловой системе

https://yoksel.github.io/url-encoder/

Попробуем?)

2021-04-05 07:58 UTC, mikhin commented on source/sass/blocks/contact-form.scss
> +  background-position: center right 20px;
background-position и background-repeat повторяются для обоих модификаторов) вынесем их повыше?

2021-04-05 07:58 UTC, mikhin commented on source/sass/blocks/form-group.scss
> +  border: none;
А это зачем? Это вроде по умолчанию)

2021-04-05 07:58 UTC, mikhin commented on source/sass/blocks/page.scss
> +.page-button {
По неймингу выглядит как отдельный БЭМ-блок. Если да, то его нужно в отдельный файл)

Еще чисто по коду непонятно что за кнопка такая page-button и для чего нужна)

2021-04-05 18:54 UTC, EzhovaT commented on source/form.html
> +                >Ссыкла на социальную сеть twitter
))Исправила

2021-04-05 19:01 UTC, EzhovaT commented on source/sass/blocks/form-group.scss
> +  border: none;
Если убираю это свойство, то у fieldset стандартная рамка есть

2021-04-05 19:05 UTC, EzhovaT commented on source/sass/blocks/page.scss
> +.page-button {
У всех кнопок одинаковый стиль, я хотела задать его через один класс... так можно делать? для этого подойдет имя класса - "standard-page-button"?

2021-04-05 19:08 UTC, EzhovaT commented on source/sass/blocks/contact-form.scss
> +  background-position: center right 20px;
Исправила

2021-04-05 19:38 UTC, EzhovaT commented on source/sass/blocks/form-group.scss
> +  border: none;
немного разобралась, оставила у fieldset только border-top, чтобы убрать <hr>

2021-04-05 19:47 UTC, EzhovaT commented on source/form.html
> +                  <p class="impression-form__label-desc">
да, точно... Исправила

2021-04-06 04:32 UTC, EzhovaT commented on source/form.html
> +          <hr class="page-form__line" />
Убрала их

2021-04-06 04:32 UTC, EzhovaT commented on source/form.html
> +                  class="form-group__input user-form__input"
Переделала

2021-04-06 04:33 UTC, EzhovaT commented on source/form.html
> +                <label
Надеюсь правильно поняла, переделала

2021-04-06 04:33 UTC, EzhovaT commented on source/form.html
> +            <ul class="form-group__list contact-form">
Исправила

2021-04-06 04:33 UTC, EzhovaT commented on source/form.html
> +                  <span class="impression-form__input-decor"></span>
Переделала

2021-04-06 04:34 UTC, EzhovaT commented on source/sass/blocks/contact-form.scss
> +  background-image: url("../img/phone.svg");
У нас не будет отдельной лекции об этом? если нет, я погуглю чуть позже, ок?

2021-04-06 13:26 UTC, mikhin requested changes

2021-04-06 13:26 UTC, mikhin commented on source/form.html
> +                <label
Не, не совсем. Сейчас получилось, что form-field по семантике это li, т.е. он может использоваться только в ul — негибко. Плюс непонятно по коду сейчас зачем нужен модификатор form-field_user.

form-label form-label_user — по идее лейбл это часть поля формы, а сейчас это отдельный бэм-блок, который непонятно как еще использовать можно + у него опять непонятный модификатор

form-input получился отдельно, но как стилизовать кастомный дизайн пока неясно.

2021-04-06 13:26 UTC, mikhin commented on source/sass/blocks/form-field.scss
> +  padding-top: 20px;
Чисто по коду непонятно зачем тут нужен единственный паддинг

2021-04-06 13:26 UTC, mikhin commented on source/sass/blocks/form-group.scss
> +  position: absolute;
А зачем абсолютное позиционирование?

2021-04-06 13:26 UTC, mikhin commented on source/sass/blocks/form-label.scss
> +.form-label_impression,
Дублирование модификаторов в обоих БЭМ-блоках говорит о том, что они получились не независимые, а на самом деле в реальной разметке, в проекте, работают рядом и одинаково. Мы не должны хотеть формально удовлетворять правилам БЭМа, и допустим просто делать уникальный БЭМ-блоки только в нейминге — это действительно должны быть независимые части интерфейсе, из которых зачем можно сложить любую композицию)

2021-04-06 13:26 UTC, mikhin commented on source/sass/blocks/form-label.scss
> +.form-input:checked + .form-label_impression::after {
По БЭМ мы не можем использовать так называемый "межблочный каскад" — когда стили одного БЭМ-блока влияют на другой. Все связки правил и селекторов должны быть только в рамках одного и того же БЭМ-блока.

2021-04-06 13:26 UTC, mikhin commented on source/sass/blocks/inner-wrapper.scss
> +.inner-wrapper {
Чисто по коду непонятно что означает имя этого элемента и для чего он используется)

2021-04-06 13:26 UTC, mikhin commented on source/sass/blocks/standard-page-button.scss
> +.standard-page-button {
Давай сделаем например просто button?)

2021-04-07 04:48 UTC, EzhovaT commented on source/sass/blocks/form-group.scss
> +  position: absolute;
не знаю как правильно это называется... у fieldset есть рамка, она идет через legend. и отступами не поднимается. а мне эта рамка нужна как разделяющая линия сверху. другого варианта я пока не нашла

2021-04-07 05:12 UTC, EzhovaT commented on source/sass/blocks/inner-wrapper.scss
> +.inner-wrapper {
забыла удалить этот файл

2021-04-07 05:12 UTC, EzhovaT commented on source/sass/blocks/standard-page-button.scss
> +.standard-page-button {
исправила

2021-04-07 05:15 UTC, EzhovaT commented on source/sass/blocks/form-field.scss
> +  padding-top: 20px;
нужно его перенести на класс с модификатором wrapper?

2021-04-07 05:23 UTC, EzhovaT commented on source/sass/blocks/form-field.scss
> +  padding-top: 20px;
исправила

2021-04-07 05:47 UTC, EzhovaT commented on source/form.html
> +                <label
значит нужно  form-field сделать ul, а li будет его элементом, потому что без ul не используется?

2021-04-07 14:00 UTC, mikhin commented on source/form.html
> +                  class="form-field__label form-field__label-contact"
непонятно что значит `form-field__label-contact`

2021-04-07 14:01 UTC, mikhin commented on source/form.html
> +                  class="form-radio"
тоже самое что и про form-input — не надо привязываться в нейминге к форме) предлагаю назвать либо `radio-field`, либо `radio-input`

2021-04-07 14:01 UTC, mikhin commented on source/form.html
> +                  class="form-radio"
тоже самое касается и чекбоксов

2021-04-07 14:02 UTC, mikhin commented on source/sass/blocks/form-checkbox.scss
> +.form-checkbox:checked + .form-field__label_type-checkbox::after {
мы не должны хотеть, чтобы стили одного БЭМ-блока влияли на стили другого БЭМ-блока

2021-04-07 14:03 UTC, mikhin commented on source/sass/blocks/form-field.scss
> +.form-field__label_type-radio {
По идее у нас два типа лейблов, и предлагаю в нейминге их не привязывать к контексту употребления, т.е. не указывать для чего они применяются, а указать какой смысл в этих лейблах

2021-04-07 14:04 UTC, mikhin commented on source/sass/blocks/form-group.scss
> +  position: absolute;
не до конца понял, но такой код — сложный и хрупкий, поэтому надо бы исправить это место. А мы можем сделать рамку на самом fieldset или его контейнере или вложенном контейнере? Неоднозначно что мы делаем границу на одном элементе, а на самом деле хотим, чтобы она была на другом элементе.

2021-04-07 14:04 UTC, mikhin commented on source/sass/blocks/form-radio.scss
> +.form-radio:checked + .form-field__label_type-radio::after {
мы не должны хотеть, чтобы стили одного БЭМ-блока влияли на стили другого БЭМ-блока

2021-04-12 08:02 UTC, EzhovaT commented on source/sass/blocks/form-group.scss
> +  position: absolute;
Исправила

2021-04-12 08:04 UTC, EzhovaT commented on source/sass/blocks/form-label.scss
> +.form-input:checked + .form-label_impression::after {
Переделала, стилизовала сам input

2021-04-12 08:04 UTC, EzhovaT commented on source/form.html
> +            <ul class="form-field">
Убрала ul и li

2021-04-12 08:04 UTC, EzhovaT commented on source/form.html
>                  <input
Исправила

2021-04-12 08:06 UTC, EzhovaT commented on source/form.html
> +              <li class="form-field__item form-field__item_user">
Исправила.  Поле отдельным блоком сделала

2021-04-12 08:06 UTC, EzhovaT commented on source/form.html
> +                  class="form-field__label form-field__label-contact"
Убрала эти модификаторы

2021-04-12 08:07 UTC, EzhovaT commented on source/form.html
> +                  class="form-radio"
Исправила

2021-04-12 08:08 UTC, EzhovaT commented on source/sass/blocks/form-checkbox.scss
> +.form-checkbox:checked + .form-field__label_type-checkbox::after {
Переделала

2021-04-12 08:12 UTC, EzhovaT commented on source/sass/blocks/form-field.scss
> +.form-field__label_type-radio {
Исправила, теперь лейблы стилизую через каскад. у родительского блока модификатор form-field_direction_vertical

2021-04-12 08:13 UTC, EzhovaT commented on source/sass/blocks/form-radio.scss
> +.form-radio:checked + .form-field__label_type-radio::after {
исправила

2021-04-12 08:18 UTC, EzhovaT commented on source/form.html
> +          <hr class="page-form__line" />
переделала

2021-04-12 08:32 UTC, merged

2021-04-12 08:40 UTC, mikhin approved these changes

2021-04-12 08:40 UTC, mikhin commented on source/sass/blocks/textarea-field.scss
> +  margin-top: 40px;
На бэм-блоках не должны хотеть задавать внешнюю геометрию)

2021-04-12 08:40 UTC, mikhin commented on source/sass/blocks/textarea-field.scss
> +  resize: none;
А это зачем?

2021-04-12 08:40 UTC, mikhin commented on source/index.html
> +                >Ссыкла на видеохостинг youtube
Вроде бы это исправляли?

2021-04-12 08:45 UTC, EzhovaT commented on source/sass/blocks/textarea-field.scss
> +  resize: none;
чтобы запретить изменение размеров textarea пользователем. Я думаю если б его нужно было оставить, в макете был бы нарисован уголок у textarea за который он растягивается

2021-04-12 08:47 UTC, EzhovaT commented on source/index.html
> +                >Ссыкла на видеохостинг youtube
извиняюсь.. не на всех страницах проверила

2021-04-12 08:50 UTC, EzhovaT commented on source/sass/blocks/textarea-field.scss
> +  margin-top: 40px;
исправила