Адаптивная сетка для страницы формы
htmlacademy-adaptive/1333157-sedona-22 pull request #9
Opened 2021-04-17 05:48 UTC by EzhovaT

2021-04-18 17:47 UTC, undgrnd requested changes

2021-04-18 17:47 UTC, undgrnd commented on source/catalog.html
> +            <li class="nav-list__item nav-list__item_spacing">
Не должны хотеть декорировать через разметку) Давай попробуем избавиться?)

2021-04-18 17:47 UTC, undgrnd commented on source/form.html
> +            <div class="form-group__field form-group__field_row">
Непонятный модификатор, чисто по неймингу. Зачем нужен?

2021-04-18 17:47 UTC, undgrnd commented on source/sass/blocks/form-field.scss
> +  @media (min-width: $desktop-width) {
Медиа-выражения для селектора должны идти перед другими вложенными селекторами

2021-04-18 17:47 UTC, undgrnd commented on source/sass/blocks/form-field.scss
> +  @media (min-width: $desktop-width) {
Непонятно почему на десктопах мы должны хотеть скрывать, а на мобильных не должны хотеть

2021-04-18 17:47 UTC, undgrnd commented on source/sass/blocks/form-group.scss
> +.form-group__field_column {
Непонятный модификатор, для чего нужен?

2021-04-18 17:47 UTC, undgrnd commented on source/sass/blocks/form-group.scss
> +    & > :first-child {
Хм, максимально-хрупкий селектор, лучше заменить на класс

2021-04-18 17:47 UTC, undgrnd commented on source/sass/blocks/page-form.scss
> +    & > :nth-child(2),
Давай все заменим на классы

2021-04-18 17:47 UTC, undgrnd commented on source/sass/blocks/text-field.scss
> +    width: 315px;
А почему именно для этих модификаторов мы хотим ширину?

2021-04-21 17:24 UTC, EzhovaT commented on source/catalog.html
> +            <li class="nav-list__item nav-list__item_spacing">
Изменила

2021-04-21 17:25 UTC, EzhovaT commented on source/form.html
> +            <div class="form-group__field form-group__field_row">
Убрала их

2021-04-21 17:25 UTC, EzhovaT commented on source/sass/blocks/form-field.scss
> +  @media (min-width: $desktop-width) {
Исправила

2021-04-21 17:26 UTC, EzhovaT commented on source/sass/blocks/form-field.scss
> +  @media (min-width: $desktop-width) {
Исправила

2021-04-21 17:26 UTC, EzhovaT commented on source/sass/blocks/form-group.scss
> +    & > :first-child {
Изменила

2021-04-21 17:26 UTC, EzhovaT commented on source/sass/blocks/text-field.scss
> +    width: 315px;
Исправила

2021-04-22 11:52 UTC, merged